### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Pythonic-Rainbow**

### CODE REVIEW

**Comment by Azanor** [comment]
What exactly is the background on this?

**Comment by 0xC0ncord** [comment]
Can we please leave politics out of programming? We are all adults here; there is no need to establish a written document telling us to act like it, especially since a project like this is just for a video game.

**Comment by Pythonic-Rainbow** [comment]
A little written document won't hurt tho 👍

**Comment by Pythonic-Rainbow** [comment]
Azanor , feel free to close this if you still find it useless , thanks!

**Comment by Solverbolt** [comment]
believing he actually cares about what any thinks on this mod, despite it being overly broken, is thinking that Trump is an actual human being and willing to give all to actually helping people instead of just himself and his family.

**Review by ghost — CHANGES_REQUESTED** [review]
Esto no es necesario

**Comment by Pythonic-Rainbow** [comment]
Yeah I don't know why I made this silly PR.

**Pull request closed without merging**
