### PR TITLE
Fix moon phases

### PR DESCRIPTION
**Pull request by yunruiwatts**
https://en.wikipedia.org/wiki/Lunar_phase - waxing is after new moon, waning is after full moon.

### CODE REVIEW

**Comment by Geethebluesky** [comment]
Yeah I can confirm that the night after getting the "Lunar, New" research note, I received a "Lunar, Waning Crescent" one so it would seem they're in the wrong order indeed.

**Comment by yunruiwatts** [comment]
It looks like both the Chinese translations are the same. The German translation seems to be missing them. I can't tell for the Japanese and Korean translations - Google translate is giving bizarre results.

**Comment by ewsmith** [comment]
third quarter and first quarter are also flipped

**Comment by yunruiwatts** [comment]
@ewsmith that's already included in this pull request

**Pull request closed without merging**
